apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.29.0"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
      dev:
        enabled: true
      ha:
        enabled: false
      standalone:
        enabled: true
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: "standard"
      serviceAccount:
        create: true
        annotations: {}
    ui:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: vault.pytt.io
          paths:
            - path: /
              pathType: Prefix
    injector:
      enabled: true
      replicas: 1
      affinity: {}
