apiVersion: v1
data:
    external_domain: ENC[AES256_GCM,data:Yp9BAyZD4/5qddIc,iv:i0ixxX1gcOejbzytwTJtBOuWD3ZNJWkGq2TuNWpWezk=,tag:phOdfKh6MwIMjB1ugGH9lg==,type:str]
    internal_domain: ENC[AES256_GCM,data:3FqX5uXzSffVFBHD,iv:TUFP72Ei354D+s3O7I/1ht1cOBtPaxoFlyE2m01iV/8=,tag:Ax/XBxWVXCDpHiotXuACLQ==,type:str]
    iot_prefix: ENC[AES256_GCM,data:DF3QiQm6hT6R/BTK,iv:r1g6B7kUfKni9BnIvetoktE1MbxgwfwT/s7UFmWDfW8=,tag:dB+2ZAzqLkd5CgqfbUIu9Q==,type:str]
    isolated_prefix: ENC[AES256_GCM,data:EvGPYwECKhNDF7D0,iv:MMQClG/HjJ5ZHpasC2kEYIa3xa2IpHlG0gDBHH0RPfA=,tag:RBNqCKhz5iJijHmtQ5UoKQ==,type:str]
    main_prefix: ENC[AES256_GCM,data:s0LPpjbTusotb5yC,iv:CZb+3ux7BrGAlMssxOEnqek/N/FWCAxR9bpZDWj34cQ=,tag:Fp06pjX+k42ejGjh5vHvOg==,type:str]
    nas_host: ENC[AES256_GCM,data:k6K48hfDwAMc6Mlhk0CdHg==,iv:vNuIuneEN2N+76KxGrfWsbQIbW+Ify37JEDPZjAMmXY=,tag:/ppYfs8xaOU37wFEngjTxQ==,type:str]
    oppe_prefix: ENC[AES256_GCM,data:/7tFAK+BGY9gQ/jH,iv:02XRT3msyRd967uSAy+45JFHXXsPM9qjDoA0bpVI1qo=,tag:g6GFJ86n5eVA2UDIX1lmIg==,type:str]
    postgresql_host: ENC[AES256_GCM,data:TmhyRSun82S+vIMjnuuwQA==,iv:JlxTdrBO8+b5yj9NQQ87ArVlin9g82HCJzIKKDUnZok=,tag:ev4ecR8uk7vDLfmsi4WX5g==,type:str]
    server_prefix: ENC[AES256_GCM,data:44nZ0wnvRYDYlb6a,iv:3k8C+cIkiZuIAq3TSA0vZxfqodt+/E4yj0aWpkwSqqc=,tag:SCZbnvADezEQ+wfXaMkG2A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: network-config
sops:
    age:
        - recipient: age1sy97xhs7my3793xjeyggvam25qhdv63f05h3f3ftevqfkjsh7cpqapg6f2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSmwreFB2dmtVMENuYmVV
            TElDWU8rSGVOTzZJZSs2OG00Y1o3dXY1cHl3ClIzVWVBTGdZVnpQK0VPUjQraHdJ
            Mnl2dVhNV2wzc3NJV2ErM1N5cGF5SkkKLS0tIHk3aVI2QzRNTHI3QnM3bThlMitX
            d0ZGRUZJVjN0QXIyMW1MVEpXdzY3ZEUKPBrprvQRTKo0EtzJCNofkD7zsX6CxfuI
            yiri4/o0YzMDcrzg/3rHgZZg9IbvzGjBq876kwGsNZAJioszhT2NEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T18:27:43Z"
    mac: ENC[AES256_GCM,data:dybZgChqdSCvFkbE4tl3LKhLVpH1VzcDjMKIe4YqN8LQlIzpc6/curM6Xj9x46dTcgq9zFXKumhnEqhSjjOgNoKNNB6DryxaDyScEt//cblqR+eaoAiPd6/jl/lwpIfzSoC02MK0/+BFuasnQMmOML4ImaEbgbcBKGE6x7lOSTA=,iv:wHNVsYG+VynMROVx87ef1Gg/Okbw1YoAMlCXEFGEjnY=,tag:ZD4L892wDXwxZzGq6bkPlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
