apiVersion: v1
kind: PersistentVolume
metadata:
 name: ollama-config-pv
spec:
 capacity:
   storage: 20Gi
 volumeMode: Filesystem
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-path
 hostPath:
   path: /var/lib/rancher/k3s/storage/ollama/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: ollama-pv
spec:
 capacity:
   storage: 1Ti
 volumeMode: Filesystem
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-path
 hostPath:
   path: /mnt/slow/ollama
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#  name: ollama-pv
# spec:
#  capacity:
#    storage: 600Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: qnap-iscsi
#  iscsi:
#    targetPortal: 192.168.1.153:3260
#    iqn: iqn.2004-04.com.qnap:ts-459uplus:iscsi.kubecsi.ca45e8
#    lun: 0
#    fsType: ext4
