apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-config-pvc
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: ollama-config-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ollama-pvc
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Ti
 storageClassName: local-path
