apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
  - port: 11434
    name: http
    targetPort: ollama-http
    protocol: TCP
    app: ollama
---
apiVersion: v1
kind: Service
metadata:
  name: web-webui
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: webui
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
