apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "8.9.1"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    image:
      repository: nextcloud
      tag: "32.0.5"
    nextcloud:
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nextcloud.pytt.io',
            'trusted_domains' => array(
              'nextcloud.pytt.io',
              'nextcloud',
            ),
            'maintenance_window_start' => 1,
            'default_phone_region' => 'NO',
            'memcache.local' => '\OC\Memcache\APCu',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => 'nextcloud-redis-master',
              'port' => 6379,
              'password' => getenv('REDIS_HOST_PASSWORD'),
            ),
          );

      host: nextcloud.pytt.io
      trustedDomains: ["nextcloud.pytt.io", "10.10.10.106"]
      # Password will be set via secret
    existingSecret:
      enabled: true
      secretName: user
      usernameKey: username
      passwordKey: password
    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: 10.10.10.106:5432
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: db
        usernameKey: user
        passwordKey: password

    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: db
        existingSecretPasswordKey: password
      master:
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 8Gi
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 50Gi
      accessMode: ReadWriteOnce
    
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 4Gi
