apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webui
  namespace: ollama
spec:
  ingressClassName: traefik
  rules:
    - host: o.pytt.io
      http:
        paths:
          - backend:
              service:
                name: webui
                port:
                  number: 8080
            path: /
            pathType: Prefix

