---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - meilisearch.yaml
  - redis.yaml
  - service.yaml
