---
# apps/base/karakeep/storage.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: karakeep-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/rancher/k3s/storage/karakeep/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: karakeep-data-pv
  resources:
    requests:
      storage: 10Gi
