apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-configs
  namespace: flux-system
spec:
  interval: 11m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/shared
  prune: true
  targetNamespace: default
  decryption:
    provider: sops
    secretRef:
      name: sops-age
