apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep
  namespace: karakeep
spec:
  ingressClassName: traefik
  rules:
    - host: karakeep.pytt.io
      http:
        paths:
          - backend:
              service:
                name: karakeep-web
                port:
                  number: 3000
            path: /
            pathType: Prefix

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep-https
  namespace: karakeep 
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - karakeep.pytt.io
      secretName: wildcard-tls-secret
  rules:
    - host: karakeep.pytt.io
      http:
        paths:
          - backend:
              service:
                name: karakeep-web
                port:
                  number: 3000 
            path: /
            pathType: Prefix
