apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      runtimeClassName: nvidia
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: jellyfin-media
        persistentVolumeClaim:
          claimName: jellyfin-pvc-old-media
      - name: jellyfin-new-media
        persistentVolumeClaim:
          claimName: jellyfin-pvc-new-media
      containers:
      - env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: JELLYFIN_PublishedServerUrl 
          value: 192.168.1.52
        - name: PGID
          value: "1000" 
        - name: PUID
          value: "1000" 
        - name: TZ
          value: Europe/Amsterdam
        securityContext:
          privileged: true 
          capabilities:
            add: ["SYS_ADMIN"]
        image: ghcr.io/linuxserver/jellyfin
        imagePullPolicy: Always
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http-tcp
          protocol: TCP
        - containerPort: 8920
          name: https-tcp
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 7359
          name: discovery-udp
          protocol: UDP      
        resources: 
          limits:
            nvidia.com/gpu: "1" 
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /config
          name: jellyfin-config
        - mountPath: /data/media
          name: jellyfin-media
        - mountPath: /data/new_media
          name: jellyfin-new-media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
