apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 8096
    - port: 7359
      targetPort: 7359
      nodePort: 7359
  selector:
    app: jellyfin
  type: ClusterIP
