apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30096
      protocol: TCP
      name: http-tcp
    - port: 8920
      targetPort: 8920
      nodePort: 30920
      protocol: TCP
      name: https-tcp
  selector:
    app: jellyfin
  type: NodePort
