apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-smb-old-media
  namespace: jellyfin
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: jellyfin-old-media-volume
    volumeAttributes:
      source: //192.168.1.152/server_media_old
    nodeStageSecretRef:
      name: smb-credentials
      namespace: jellyfin
      #---
      #apiVersion: v1
      #kind: PersistentVolume
      #metadata:
      #  name: jellyfin-pv-smb-new-media
      #  namespace: jellyfin
      #spec:
      #  capacity:
      #    storage: 8Ti
      #  accessModes:
      #    - ReadWriteMany
      #  persistentVolumeReclaimPolicy: Retain
      #  mountOptions:
      #    - dir_mode=0777
      #    - file_mode=0777
      #    - vers=3.0
      #  csi:
      #    driver: smb.csi.k8s.io
      #    readOnly: false
      #    volumeHandle: jellyfin-new-media-volume
      #    volumeAttributes:
      #      source: //192.168.1.152/server_media_new
      #    nodeStageSecretRef:
      #      name: smb-credentials
      #      namespace: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-old-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-pv-smb-old-media
  storageClassName: ""
      #---
      #apiVersion: v1
      #kind: PersistentVolumeClaim
      #metadata:
      #  name: jellyfin-pvc-new-media
      #  namespace: jellyfin
      #spec:
      #  accessModes:
      #    - ReadWriteMany
      #  resources:
      #    requests:
      #      storage: 1Ti
      #  volumeName: jellyfin-pv-smb-new-media
#  storageClassName: ""
